#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-bundle-screenshots
Version  : 1
Release  : 1
URL      : http://localhost/cgit/projects/clr-bundle-screenshots/snapshot/clr-bundle-screenshots-1.tar.gz
Source0  : http://localhost/cgit/projects/clr-bundle-screenshots/snapshot/clr-bundle-screenshots-1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-3.0 MIT
Requires: clr-bundle-screenshots-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the clr-bundle-screenshots package.
Group: Data

%description data
data components for the clr-bundle-screenshots package.


%prep
%setup -q -n clr-bundle-screenshots-1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553213072
export LDFLAGS="${LDFLAGS} -fno-lto"
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1553213072
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/clear/bundle-screenshots/desktop/default.png
